import Header from "@/components/header/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Solomon Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="logo/logo.png" type="image/png" sizes="50*50" />
      </head>
      <body
        suppressHydrationWarning={true}
        className={`${inter.className} bg-gray-100   p-1`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
